server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/campus_errand?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: cjp

mybatis:
#  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yolo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true